WebBanHang/Areas/Admin/Controllers/KhachHangController.cs
using WebBanHang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: Admin/KhachHang
        dbShopQuanAoDataContext data = new dbShopQuanAoDataContext();
        // GET: KhachHang
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            var khachhang = data.KhachHangs.OrderBy(n => n.MaKH);
            return View(khachhang);
        }
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            var khachhang = (from s in data.KhachHangs
                             where s.MaKH == id
                             select s).FirstOrDefault();
            if (khachhang == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(khachhang);
        }
        [HttpPost]
        public ActionResult Edit(int id, KhachHang khachhang)
        {
            khachhang = (from s in data.KhachHangs where s.MaKH == id select s).FirstOrDefault();
            UpdateModel(khachhang);
            data.SubmitChanges();
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            KhachHang khachhang = (from s in data.KhachHangs
                                   where s.MaKH == id
                                   select s).FirstOrDefault();
            var listbl = data.BinhLuans.Where(s => s.MaKH == id).ToList();
            var listhd = data.HoaDons.Where(s => s.MaKH == id).ToList();
            try
            {
                foreach (var item in listhd.ToList())
                {
                    var chitiethoadon = data.ChiTietHoaDons.Where(s => s.MaHD == item.MaHD).ToList();
                    data.ChiTietHoaDons.DeleteAllOnSubmit(chitiethoadon);
                    data.SubmitChanges();
                }
                foreach (var item in listhd.ToList())
                {
                    data.HoaDons.DeleteAllOnSubmit(listhd);
                    data.SubmitChanges();
                }
                foreach (var item in listbl.ToList())
                {
                    data.BinhLuans.DeleteAllOnSubmit(listbl);
                    data.SubmitChanges();
                }
                data.KhachHangs.DeleteOnSubmit(khachhang);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Areas/Admin/Views/KhachHang/Edit.cshtml
@model WebBanHang.Models.KhachHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Sửa thông tin khách hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Edit", "KhachHang", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.HoTen)
                <div class="form-horizontal">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Tên khách hàng</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.HoTen, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.HoTen)
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="typeahead">Username</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.TenDangNhap, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.TenDangNhap)
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="typeahead">Mật khẩu</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.MatKhau, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.MatKhau)
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="typeahead">Địa chỉ</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.DiaChi, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.DiaChi)
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="typeahead">Số điện thoại</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.SoDienThoai, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.SoDienThoai)
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="typeahead">Email</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Email, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.Email)
                            </div>
                        </div>
                        <div class="form-actions">
                            <a style="background-color:#702222; text-decoration: none; color: #fff" class="btn" href="@Url.Action("Index", "KhachHang")">Back to list</a>
                            <button type="submit" class="btn btn-primary" name="btnSubmit">Submit</button>
                            <button type="reset" class="btn">Reset</button>
                        </div>
                    </fieldset>
                </div>
            }
        </div>
    </div><!--/span-->
</div><!--/row-->

WebBanHang/Areas/Admin/Views/KhachHang/Index.cshtml
@model IEnumerable<WebBanHang.Models.KhachHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Admin/Home">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><a href="#">Khách hàng</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>Khách hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>

        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Tên khách hàng</th>
                        <th>Username</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaKH">
                            <td>@Html.DisplayFor(modelItem => item.HoTen)</td>
                            <td>@Html.DisplayFor(modelItem => item.TenDangNhap)</td>
                            <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
                            <td>@Html.DisplayFor(modelItem => item.SoDienThoai)</td>
                            <td>@Html.DisplayFor(modelItem => item.Email)</td>
                            <td>
                                <a class="btn btn-info" href="/Admin/KhachHang/Edit/@item.MaKH"><i class="halflings-icon white edit"></i> Sửa</a>
                                <a class="btn btn-danger" data-ajax="true" data-ajax-complete="$('#row_@item.MaKH').remove()" data-ajax-confirm="Bạn có muốn xóa bản ghi này không?" data-ajax-method="Delete" href="/Admin/KhachHang/Delete/@item.MaKH">
                                    <i class="halflings-icon white trash"></i> Xóa
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <p>Lưu ý: Phải xóa toàn bộ thông tin có liên quan trong Khách hàng mới có thể tiến hành xóa.</p>
        </div>
    </div><!--/span-->
</div><!--/row-->