WebBanHang/Areas/Admin/Controllers/HoaDonController.cs
using WebBanHang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class HoaDonController : Controller
    {
        // GET: Admin/HoaDon
        dbShopQuanAoDataContext data = new dbShopQuanAoDataContext();
        // GET: HoaDon
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            var hoadons = data.HoaDons.OrderBy(h => h.MaHD);
            return View(hoadons);
        }
        public ActionResult Details(int id)
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }

            var hoadon = (from s in data.HoaDons
                          where s.MaHD == id
                          select s).FirstOrDefault();
            var list = data.ChiTietHoaDons.Where(s => s.MaHD == hoadon.MaHD).ToList();
            var khachhang = (from s in data.KhachHangs
                             where s.MaKH == hoadon.MaKH
                             select s).FirstOrDefault();
            ViewBag.name = khachhang.HoTen;
            ViewBag.address = khachhang.DiaChi;
            ViewBag.phone = khachhang.SoDienThoai;
            return View(list);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            var hoadon = (from s in data.HoaDons
                          where s.MaHD == id
                          select s).FirstOrDefault();
            return View(hoadon);
        }
        [HttpPost]
        public ActionResult Edit(int id, HoaDon hoadon)
        {
            hoadon = (from s in data.HoaDons
                      where s.MaHD == id
                      select s).FirstOrDefault();
            UpdateModel(hoadon);
            data.SubmitChanges();
            ViewBag.ThongBao = "SUCCESS";
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id, HoaDon hoadons)
        {
            hoadons = (from s in data.HoaDons
                       where s.MaHD == id
                       select s).FirstOrDefault();
            ChiTietHoaDon chitiethoadon = (from s in data.ChiTietHoaDons where s.MaHD == hoadons.MaHD select s).FirstOrDefault();
            if (hoadons == null)
            {
                return HttpNotFound();
            }
            else
            {
                try
                {
                    if (chitiethoadon != null)
                    {

                        var list = data.ChiTietHoaDons.Where(s => s.MaHD == hoadons.MaHD).ToList();
                        data.ChiTietHoaDons.DeleteAllOnSubmit(list);
                        data.SubmitChanges();
                    }
                    data.HoaDons.DeleteOnSubmit(hoadons);
                    data.SubmitChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View();
                }
            }
        }
    }
}

WebBanHang/Areas/Admin/Views/HoaDon/Details.cshtml
@model IEnumerable<WebBanHang.Models.ChiTietHoaDon>

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="index.php">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        Hóa đơn
    </li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>Chi tiết hóa đơn</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>

        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Mã Sản Phẩm</th>
                        <th>Tên Sản phẩm</th>
                        <th>Kích thước</th>
                        <th>Đơn giá(VNĐ/cái)</th>
                        <th>Số lượng</th>
                        <th>Tổng tiền(VNĐ)</th>
                    </tr>
                </thead> 
                <tbody>
                    @{
                        int? sum = 0;
                        int id = 0;
                        foreach (var item in Model)
                        {


                            var s = @item.DonGia * @item.SoLuong;
                            var d = @item.DonGia;
                            string dongiafm = $"{d:N}";
                            string tongtien = $"{s:N}";
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.SanPham.MaSP)</td>
                                <td>@Html.DisplayFor(modelItem => item.TenSP)</td>
                                <td>@Html.DisplayFor(modelItem => item.Size.TenS)</td>                                   
                                <td>@dongiafm ₫</td>
                                <td>@Html.DisplayFor(modelItem => item.SoLuong)</td>
                                <td>@tongtien ₫</td>
                                <td></td>
                            </tr>
                            sum += @item.DonGia * @item.SoLuong;
                            id = @item.MaHD;
                        }
                        string formatted = $"{sum:N}";
                        <h2>Mã đơn hàng: @id</h2>
                        <h2>Tên khách hàng: @ViewBag.name</h2>
                        <h2>Địa chỉ: @ViewBag.address</h2>
                        <h2>Số điện thoại: @ViewBag.phone</h2>
                        <h2 style="color:red">Tổng giá trị đơn hàng: @formatted ₫</h2>
                    }
                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div><!--/row-->

WebBanHang/Areas/Admin/Views/HoaDon/Edit.cshtml
@model WebBanHang.Models.HoaDon

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Sửa thông tin đơn hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("Edit", "HoaDon", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.MaHD)
                <div class="form-horizontal">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Tình trạng giao hàng</label>
                            <div class="controls">
                                @Html.DropDownListFor(model => model.TrangThai, new List<SelectListItem>
                               {
                                   new SelectListItem() { Text = "Đã giao hàng", Value = "true"},
                                   new SelectListItem() { Text = "Chưa giao hàng", Value = "false"}
                               })
                            </div>
                            <p style="color:red;padding-left: 240px;">@ViewBag.ThongBao</p>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Tình trạng thanh toán</label>
                            <div class="controls">
                                @Html.DropDownListFor(model => model.DaThanhToan, new List<SelectListItem>
                        {
                            new SelectListItem() { Text = "Đã thanh toán", Value = "true"},
                            new SelectListItem() { Text = "Chưa thanh toán", Value = "false"}
                        })
                            </div>
                            <p style="color:red;padding-left: 240px;">@ViewBag.ThongBao</p>
                        </div>
                        <div class="form-actions">
                            <a style="background-color:#702222; text-decoration: none; color: #fff" class="btn" href="@Url.Action("Index", "HoaDon")">Back to list</a>
                            <button type="submit" class="btn btn-primary" name="btnSubmit">Submit</button>
                            <button type="reset" class="btn">Reset</button>
                        </div>
                    </fieldset>
                </div>
            }
        </div>
    </div><!--/span-->
</div><!--/row-->

WebBanHang/Areas/Admin/Views/HoaDon/Index.cshtml
@model IEnumerable<WebBanHang.Models.HoaDon>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Admin/Home">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        <a href="/Admin/HoaDon">Hóa đơn</a>
    </li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>Danh sách đơn hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>

        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Mã hóa đơn</th>
                        <th>Ngày đặt hàng</th>
                        <th>Khách hàng</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Ghi chú</th>
                        <th>Tình trạng</th>
                        <th>Tình trạng thanh toán</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaHD">
                            <td>@Html.DisplayFor(modelItem => item.MaHD)</td>
                            <td>@Html.DisplayFor(modelItem => item.NgayLapHD)</td>
                            <td>@Html.DisplayFor(modelItem => item.KhachHang.HoTen)</td>
                            <td>@Html.DisplayFor(modelItem => item.KhachHang.DiaChi)</td>
                            <td>@Html.DisplayFor(modelItem => item.KhachHang.SoDienThoai)</td>
                            <td>@Html.DisplayFor(modelItem => item.GhiChu)</td>
                            <td>@Html.DisplayFor(model => item.TrangThai)</td>
                            <td>@Html.DisplayFor(model => item.DaThanhToan)</td>
                            <td>
                                <a class="btn" href="/Admin/HoaDon/Details/@item.MaHD">Ctiết</a>
                                <a class="btn btn-info" href="/Admin/HoaDon/Edit/@item.MaHD"><i class="halflings-icon white edit"></i> Sửa</a>
                                <a class="btn btn-danger" data-ajax="true" data-ajax-complete="$('#row_@item.MaHD').remove()" data-ajax-confirm="Bạn có muốn xóa bản ghi này không?" data-ajax-method="Delete" href="/Admin/HoaDon/Delete/@item.MaHD">
                                    <i class="halflings-icon white trash"></i> Xóa
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div><!--/row-->