WebBanHang/Areas/Admin/Models/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebBanHang.Models;
using System.Web.Mvc;
using System.Data.SqlClient;

namespace WebBanHang.Areas.Admin.Models
{    
    public class DeleteViewModel
    {
        dbShopQuanAoDataContext data = new dbShopQuanAoDataContext();
        public void DeleteSize(int id)
        {
            var sanphamsizes = data.SanPhams
            .Join(data.SanPhamSizes,
              post => post.MaSP,
              metal => metal.MaSP,
             (post, metal) => new { SanPham = post, SanPhamSize = metal })
           .Where(postAndMeta => postAndMeta.SanPham.MaSP == id);
            foreach (var item in sanphamsizes)
            {
                data.SanPhamSizes.DeleteOnSubmit(item.SanPhamSize);
            }
            data.SubmitChanges();
        }
        public void DeleteHinhAnh(int id)
        {
            var hinhanhs = data.SanPhams
            .Join(data.HinhAnhs,
              post => post.MaSP,
              metal => metal.MaSP,
             (post, metal) => new { SanPham = post, HinhAnh = metal })
           .Where(postAndMeta => postAndMeta.SanPham.MaSP == id);
            foreach (var item in hinhanhs)
            {
                data.HinhAnhs.DeleteOnSubmit(item.HinhAnh);
            }
            data.SubmitChanges();
        }
        public void DeleteBinhLuan(int id)
        {
            var binhluans = data.SanPhams
            .Join(data.BinhLuans,
              post => post.MaSP,
              metal => metal.MaSP,
             (post, metal) => new { SanPham = post, BinhLuan = metal })
           .Where(postAndMeta => postAndMeta.SanPham.MaSP == id);
            foreach (var item in binhluans)
            {
                data.BinhLuans.DeleteOnSubmit(item.BinhLuan);
            }
            data.SubmitChanges();
        }

        public void DeleteChiTietHoaDon(int id)
        {
            var chitiethoadons = data.SanPhams
            .Join(data.ChiTietHoaDons,
              post => post.MaSP,
              metal => metal.MaSP,
             (post, metal) => new { SanPham = post, ChiTietHoaDon = metal })
           .Where(postAndMeta => postAndMeta.SanPham.MaSP == id);
            foreach (var item in chitiethoadons)
            {
                data.ChiTietHoaDons.DeleteOnSubmit(item.ChiTietHoaDon);
            }
            data.SubmitChanges();
        }
        public void DeleteSanPham(int id)
        {
            var sanpham = (from s in data.SanPhams
                          where s.MaSP == id
                          select s).FirstOrDefault();
            data.SanPhams.DeleteOnSubmit(sanpham);
            data.SubmitChanges();
        }
    }
}

WebBanHang/Areas/Admin/Controllers/KichThuocController.cs
using WebBanHang.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class KichThuocController : Controller
    {
        // GET: Admin/KichThuoc
        dbShopQuanAoDataContext data = new dbShopQuanAoDataContext();
        // GET: Size
        public ActionResult Index()
        {
            var sizes = data.Sizes.OrderBy(n => n.MaS);
            return View(sizes);
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Create(Size sizes)
        {

            data.Sizes.InsertOnSubmit(sizes);
            if (String.IsNullOrEmpty(sizes.TenS))
            {
                ViewBag.ThongBao = "Chưa nhập";
            }
            else
            {
                try
                {
                    data.SubmitChanges();
                    ViewBag.ThongBao = "SUCCESS";
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    ViewBag.ThongBao = "Lỗi nhập size(vd: xxl... không lớn hơn 3 chữ cái)";
                }
            }
            return this.Create();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null || Session["Taikhoanadmin"].ToString() == "")
            {
                return Redirect("~/Admin/Login");
            }
            var sizes = (from s in data.Sizes
                         where s.MaS == id
                         select s).FirstOrDefault();
            if (sizes == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sizes);
        }
        [HttpPost]
        public ActionResult Edit(int id, Size sizes)
        {
            sizes = (from s in data.Sizes
                     where s.MaS == id
                     select s).FirstOrDefault();
            UpdateModel(sizes);
            if (String.IsNullOrEmpty(sizes.TenS))
            {
                ViewBag.ThongBao = "Chưa nhập";
            }
            else
            {
                try
                {
                    data.SubmitChanges();
                    ViewBag.ThongBao = "SUCCESS";
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    ViewBag.ThongBao = "Lỗi nhập size(vd: xxl... không lớn hơn 3 chữ cái)";
                }
            }
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id, Size sizes)
        {
            sizes = (from s in data.Sizes
                     where s.MaS == id
                     select s).FirstOrDefault();
            SanPhamSize sanphamsizes = data.SanPhamSizes.SingleOrDefault(n => n.MaS == id);
            if (sanphamsizes != null)
            {
                data.SanPhamSizes.DeleteOnSubmit(sanphamsizes);
                data.SubmitChanges();
            }
            data.Sizes.DeleteOnSubmit(sizes);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

WebBanHang/Areas/Admin/Views/KichThuoc/Create.cshtml
@model WebBanHang.Models.Size

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thêm kích thước</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-horizontal">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Tên Kích thước</label>
                            <div class="controls">    
                                    @Html.EditorFor(model => model.TenS, new { @class = "span6 typeahead" })
                                    @Html.ValidationMessageFor(model => model.TenS)
                                </div>
                            <p style="color:red;padding-left: 182px;">@ViewBag.ThongBao</p>
                        </div>
                        <div class="form-actions">
                            <a style="background-color:#702222; text-decoration: none; color: #fff" class="btn" href="@Url.Action("Index", "KichThuoc")">Back to list</a>
                            <button type="submit" class="btn btn-primary" name="btnSubmit">Submit</button>
                            <button type="reset" class="btn">Reset</button>
                        </div>
                    </fieldset>
                </div>
            }


        </div>
    </div><!--/span-->
</div><!--/row-->

WebBanHang/Areas/Admin/Views/KichThuoc/Delete.cshtml
@model WebBanHang.Models.Size

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            <p style="color:red;padding-left: 240px;">@ViewBag.ThongBao</p>|
        </div>
    }
</div>

WebBanHang/Areas/Admin/Views/KichThuoc/Edit.cshtml
@model WebBanHang.Models.Size

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Sửa kích thước</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-horizontal">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Tên kích thước</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.TenS, new { @class = "span6 typeahead" })
                                @Html.ValidationMessageFor(model => model.TenS)
                            </div>
                        </div>
                        <p style="color:red;padding-left: 240px;">@ViewBag.ThongBao</p>
                        <div class="form-actions">
                            <a style="background-color:#702222; text-decoration: none; color: #fff" class="btn" href="@Url.Action("Index", "KichThuoc")">Back to list</a>
                            <button type="submit" class="btn btn-primary" name="btnSubmit">Submit</button>
                            <button type="reset" class="btn">Reset</button>
                        </div>
                    </fieldset>
                </div>
            }
        </div>
    </div><!--/span-->
</div><!--/row-->

WebBanHang/Areas/Admin/Views/KichThuoc/Index.cshtml
@model IEnumerable<WebBanHang.Models.Size>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Admin/Index">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        Sản phẩm
        <i class="icon-angle-right"></i>
    </li>
    <li><a href="#">Kích thước</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>Kích thước</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>

        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>
                            Mã kích thước       
                        </th>
                        <th>
                            Tên kích thước
                        </th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaS">
                            <td>
                                @item.MaS
                            </td>
                            <td>
                                @item.TenS
                            </td>
                            <td>
                                <a class="btn btn-info" href="/Admin/KichThuoc/Edit/@item.MaS"><i class="halflings-icon white edit"></i> Sửa</a>
                                <a class="btn btn-danger" data-ajax="true" data-ajax-complete="$('#row_@item.MaS').remove()" data-ajax-confirm="Bạn có muốn xóa bản ghi này không?" data-ajax-method="Delete" href="/Admin/KichThuoc/Delete/@item.MaS">
                                    <i class="halflings-icon white trash"></i> Xóa
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <p>Lưu ý: Phải xóa toàn bộ sản phẩm hay danh mục có liên quan trong Size mới có thể tiến hành xóa.</p>
            <a class="btn btn-success" href="@Url.Action("Create","KichThuoc")">
                <i class="halflings-icon white zoom-in"></i>Thêm mới
            </a>
        </div>
    </div><!--/span-->
</div><!--/row-->